version: '3.9'
services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfile
    image: postgres:latest
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: deploy
      POSTGRES_DB: resume
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
